// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwoE6rRC5tf3aX5N9qHKHgnW2liCMTAsA',
    appId: '1:352762993480:android:81335a1dec9f3ee6c2317d',
    messagingSenderId: '352762993480',
    projectId: 'ricechat-38535',
    storageBucket: 'ricechat-38535.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFwHYhB-12KML_kyCwo8fgruVAsxTlO2U',
    appId: '1:352762993480:ios:b3f3258441da6feec2317d',
    messagingSenderId: '352762993480',
    projectId: 'ricechat-38535',
    storageBucket: 'ricechat-38535.firebasestorage.app',
    androidClientId: '352762993480-iqva8b7sh3ibfjltari72ckcig13kkk8.apps.googleusercontent.com',
    iosClientId: '352762993480-sph8fie14e3hpedvu5s6tithlmfg83lu.apps.googleusercontent.com',
    iosBundleId: 'com.example.riceChat',
  );

}